# Generated by Django 6.0.5 on 2026-05-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrixJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('prix_min', models.DecimalField(decimal_places=3, max_digits=8)),
                ('prix_max', models.DecimalField(decimal_places=3, max_digits=8)),
                ('prix_moyen', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantite_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('acheteur', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
