# Generated by Django 6.0.5 on 2026-05-12 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terrain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantite_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qualite', models.CharField(choices=[('A', 'Grade A — Bouquet / Fresh'), ('B', 'Grade B — Distillation'), ('C', 'Grade C — Pétales séchés / Dried petals')], default='A', max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='terrain.parcelle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
