# Generated by Django 6.0.5 on 2026-05-12 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terrain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('categorie', models.CharField(choices=[('engrais', 'Engrais / Fertilizer'), ('pesticide', 'Pesticide / Medication'), ('eau', 'Eau / Water'), ('carburant', 'Carburant / Fuel'), ('main_oeuvre', "Main d'œuvre / Labor"), ('materiel', 'Matériel / Equipment'), ('autre', 'Autre / Other')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fournisseur', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='terrain.parcelle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
