# Generated by Django 6.0.5 on 2026-05-12 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin', models.CharField(blank=True, max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('tarif_jour', models.DecimalField(decimal_places=2, default=30, max_digits=8)),
                ('actif', models.BooleanField(default=True)),
                ('date_embauche', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('avance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='employes.employe')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
