# Generated by Django 6.0.5 on 2026-05-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('superficie_ha', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nb_pieds', models.IntegerField(default=0)),
                ('date_plantation', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'En culture / Active'), ('repos', 'En repos / Resting'), ('traitement', 'En traitement / Treatment'), ('renouvellement', 'À renouveler / To renew')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
